### ISSUE TITLE
copy with copyartifacts doubles the files

### ISSUE THREAD

**Issue by dogo77** [sbarakat/beets-copyartifacts#33]
Hi, i have an strange issue here.
archlinux
beets version 1.4.3
Python version 3.6.0
plugins: acousticbrainz, bucket, chroma, copyartifacts, discogs, fetchart, fuzzy, inline, lastgenre, lastimport, lyrics, missing, replaygain, web

copyartifacts:
     extensions: .*
     print_ignored: yes

beets-copyartifacts==0.1.2
build as said on the homepage with 
`
git clone https://github.com/sbarakat/beets-copyartifacts.git
cd beets-copyartifacts
python setup.py install
`
, but this does not copy the plugin to /usr/lib/python3.6/site-packages/beetsplug
so i copied it to /home/user/Musik/beets/
and made an entry in config.yaml
`pluginpath: /home/user/Musik/beets`

when i try to import a directory with following content (just because it's so short):
`
'01 - Flava (Radio 7 Edit) - Peter Andre.ogg' 
'02 - Flava (Benz Mix) - Peter Andre.ogg'  
'03 - Flava (Richie P Mix) - Peter Andre.ogg'  
'04 - Flava (Crichton & Morris 12 Mix) - Peter Andre.ogg'
'Peter Andre - Flava.ogg.m3u'
cover.jpg
`
i get the following error

`
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 124, in wrapper
    return func(*args, **kwargs)
TypeError: process_events() got an unexpected keyword argument 'lib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1209, in main
    _raw_main(args)
  File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line 1198, in _raw_main
    plugins.send('cli_exit', lib=lib)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 452, in send
    result = handler(**arguments)
  File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/daniel/Musik/beets/copyartifacts.py", line 127, in process_events
    self.process_artifacts(item['files'], item['mapping'], False)
  File "/home/daniel/Musik/beets/copyartifacts.py", line 161, in process_artifacts
    dest_file = beets.util.unique_path(dest_file)
  File "/usr/lib/python3.6/site-packages/beets/util/__init__.py", line 512, in unique_path
    match = re.search(br'\.(\d)+$', base)
  File "/usr/lib/python3.6/re.py", line 182, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a bytes pattern on a string-like object
`

right after selecting [A]pply in dialog.

AND THEN:
i have all the files doubled in the new location :(
and the "artifacts" are missing :-((
`
'01 Flava (Radio 7_ Edit).ogg'
'01 - Flava (Radio 7 Edit) - Peter Andre.ogg'
'02 Flava (Benz Mix).ogg'
'02 - Flava (Benz Mix) - Peter Andre.ogg'
'03 Flava (Richie P Mix).ogg'
'03 - Flava (Richie P Mix) - Peter Andre.ogg'
'04 - Flava (Crichton & Morris 12 Mix) - Peter Andre.ogg'
'04 Flava (Crichton & Morris 7_ Mix).ogg'
 cover.jpg
`

what did i do wrong?

**Comment by thomwiggers** [comment]
Copyartifacts doesn't support python 3. You can't use it with the version of copyartifacts from the repository.

On 21 February 2017 00:14:08 CET, dogo77 <notifications@github.com> wrote:
>Hi, i have an strange issue here.
>archlinux
>beets version 1.4.3
>Python version 3.6.0
>plugins: acousticbrainz, bucket, chroma, copyartifacts, discogs,
>fetchart, fuzzy, inline, lastgenre, lastimport, lyrics, missing,
>replaygain, web
>
>copyartifacts:
>     extensions: .*
>     print_ignored: yes
>
>
>beets-copyartifacts==0.1.2
>build as said on the homepage with 
>`
>git clone https://github.com/sbarakat/beets-copyartifacts.git
>cd beets-copyartifacts
>python setup.py install
>`
>, but this does not copy the plugin to
>/usr/lib/python3.6/site-packages/beetsplug
>so i copied it to /home/user/Musik/beets/
>and made an entry in config.yaml
>`pluginpath: /home/user/Musik/beets`
>
>when i try to import a directory with following content (just because
>it's so short):
>`
>'01 - Flava (Radio 7 Edit) - Peter Andre.ogg' 
>'02 - Flava (Benz Mix) - Peter Andre.ogg'  
>'03 - Flava (Richie P Mix) - Peter Andre.ogg'  
>'04 - Flava (Crichton & Morris 12 Mix) - Peter Andre.ogg'
>'Peter Andre - Flava.ogg.m3u'
>cover.jpg
>`
>i get the following error
>
>`
>Traceback (most recent call last):
>File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 124, in
>wrapper
>    return func(*args, **kwargs)
>TypeError: process_events() got an unexpected keyword argument 'lib'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/usr/bin/beet", line 11, in <module>
>    load_entry_point('beets==1.4.3', 'console_scripts', 'beet')()
>File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line
>1209, in main
>    _raw_main(args)
>File "/usr/lib/python3.6/site-packages/beets/ui/__init__.py", line
>1198, in _raw_main
>    plugins.send('cli_exit', lib=lib)
>File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 452, in
>send
>    result = handler(**arguments)
>File "/usr/lib/python3.6/site-packages/beets/plugins.py", line 130, in
>wrapper
>    return func(*args, **kwargs)
>File "/home/daniel/Musik/beets/copyartifacts.py", line 127, in
>process_events
>    self.process_artifacts(item['files'], item['mapping'], False)
>File "/home/daniel/Musik/beets/copyartifacts.py", line 161, in
>process_artifacts
>    dest_file = beets.util.unique_path(dest_file)
>File "/usr/lib/python3.6/site-packages/beets/util/__init__.py", line
>512, in unique_path
>    match = re.search(br'\.(\d)+$', base)
>  File "/usr/lib/python3.6/re.py", line 182, in search
>    return _compile(pattern, flags).search(string)
>TypeError: cannot use a bytes pattern on a string-like object
>`
>
>right after selecting [A]pply in dialog.
>
>AND THEN:
>i have all the files doubled in the new location :(
>and the "artifacts" are missing :-((
>`
>'01 Flava (Radio 7_ Edit).ogg'
>'01 - Flava (Radio 7 Edit) - Peter Andre.ogg'
>'02 Flava (Benz Mix).ogg'
>'02 - Flava (Benz Mix) - Peter Andre.ogg'
>'03 Flava (Richie P Mix).ogg'
>'03 - Flava (Richie P Mix) - Peter Andre.ogg'
>'04 - Flava (Crichton & Morris 12 Mix) - Peter Andre.ogg'
>'04 Flava (Crichton & Morris 7_ Mix).ogg'
> cover.jpg
>`
>
>what did i do wrong?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sbarakat/beets-copyartifacts/issues/33

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dogo77** [comment]
oh.
After reading https://github.com/sbarakat/beets-copyartifacts/pull/32 i thought that was fixed in current dev version.
so i'll have to wait…

**Comment by agsimmons** [comment]
@thomwiggers Are you planning on moving beets-copyartifacts to Python 3 in the future? The Beets devs have indicated that they will begin deprecating Python 2 soon https://twitter.com/b33ts/status/818485319725182977

**Comment by thomwiggers** [comment]
@agsimmons dunno why you're asking me, this isn't my package.
