### ISSUE TITLE
pyton 3

### ISSUE THREAD

**Issue by satfreak** [sbarakat/beets-copyartifacts#50]
In python3 i get the following error, when using beets

error loading plugin copyartifacts:
Traceback (most recent call last):
  File "/opt/local/lib/python3.7/site-packages/beets/plugins.py", line 273, in load_plugins
    namespace = __import__(modname, None, None)
  File "/opt/local/lib/python3.7/site-packages/beetsplug/copyartifacts.py", line 141
    print 'Ignored files:'

This is showing on every command i do with beet

**Comment by thomwiggers** [comment]
See #31
